server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      routes:
        - id: polynome-service
          uri: http://localhost:8082
          predicates:
            - Path=/polynomes/**
        - id: racine-service
          uri: http://localhost:8083
          predicates:
            - Path=/racines/**
        - id: factorisation-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/factorisation/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true